In [1]:
import numpy as np

In [6]:
a = np.array([1,1,1])
b = np.array([2,2,2])

c = np.vstack((a,b))
print(a.shape,b.shape,c.shape)
print(c)

(3,) (3,) (2, 3)
[[1 1 1]
 [2 2 2]]


In [7]:
d = np.hstack((a,b))
print(d)

[1 1 1 2 2 2]


In [13]:
print(a[np.newaxis,:])
print(a[:,np.newaxis])

[[1 1 1]]
[[1]
 [1]
 [1]]


In [17]:
e = np.concatenate((a,b,b),axis =0)
print(e)

[1 1 1 2 2 2 2 2 2]
