In [1]:
import numpy as np

In [6]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a, b)
c = a-b  
print(c)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]


In [10]:
c = 10 * np.sin(a)  #sin , cos , tan
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [13]:
print(b)
print(b<3)

[0 1 2 3]
[ True  True  True False]


In [18]:
a = np.array([[1,1],
              [2,2]])
b = np.arange(4).reshape((2,2))

print(a)
print(b)

print(a*b)          #逐個相乘
print(np.dot(a,b))  #矩陣相乘 np.dot(m1,m2)

[[1 1]
 [2 2]]
[[0 1]
 [2 3]]
[[0 1]
 [4 6]]
[[2 4]
 [4 8]]


In [30]:
a = np.random.random((2,4))
print(a)
print('sum: ',np.sum(a,axis = 1))
print('min: ',np.min(a,axis = 0))
print('max: ',np.max(a,axis = 1))  # axis 用法 0: column 計算 ,1: row 計算

[[0.89161793 0.98684204 0.62286153 0.32221519]
 [0.91750966 0.67401994 0.14729259 0.90869892]]
sum:  [2.82353668 2.6475211 ]
min:  [0.89161793 0.67401994 0.14729259 0.32221519]
max:  [0.98684204 0.91750966]


In [34]:
a = np.arange(2,14).reshape(3,4)
print(a)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [48]:
print(np.argmin(a))  #最小值得index
print(np.argmax(a))  #最大值得index
print(np.mean(a))    #mean值
print(np.cumsum(a))  #累加值
print(np.diff(a))    #累差值  （與前一項的差）
print(np.nonzero(a)) #非零值的行列
a = np.arange(14,2,-1).reshape(3,4)
print(a)
print(np.sort(a))   #逐行排序

print((a.T).dot(a))
print(np.clip(a,5,9))  # arg = a,a_min,a_max,out = None



11
0
8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
