In [1]:
import numpy as np

In [2]:
# one dim


a = np.arange(3,15)
print(a)
print(a[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [11]:
# two dim

b = np.arange(3,15).reshape(3,4)
print(b)
print(b[1])
print(b[1][2])  
print(b[1,2])  # b[1,2] = b[1][2]
print(b[2,:])  # : = all elements
print(b[:,:])
print(b[1,0:2])  # 0:2  = start :end

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 7  8  9 10]
9
9
[11 12 13 14]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[7 8]


In [17]:
for row in b:
    print(row)
    
for col in b.T:
    print(col)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [18]:
print(b)
print(b.flatten())
for item in b.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
