In [1]:
import numpy as np

In [2]:
# list to numpy
array = np.array([[1,2,3],
                  [2,3,4]])
print(array)

[[1 2 3]
 [2 3 4]]


In [6]:
# 基礎numpy屬性
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)

number of dim: 2
shape: (2, 3)
size: 6


In [19]:
#Numpy 創建 
a = np.array([[1,2,3],
              [2,3,4]],dtype = np.int)  #指定data type
print(a.dtype)
print(a)

int64
[[1 2 3]
 [2 3 4]]


In [30]:
a = np.zeros((3,4),dtype = np.int16)   #零矩陣 (row , col)
print(a)

a = np.empty((3,4),dtype = np.float)   #為非常接近0的矩陣
print(a)

a = np.arange(10,18,2).reshape((2,2))  # arange(start,end,skip) , reshape((row,col))
print(a)

a = np.linspace(1,10,20).reshape(4,5)  #linspace 線段,(start,end, 幾段）
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10 12]
 [14 16]]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]
